apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: demo-provisioner-operator
    app.kubernetes.io/part-of: demo-provisioner-operator
    app.kubernetes.io/managed-by: kustomize
  name: demo-provisioner-operator-system
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: demo-provisioner-catalog
  namespace: demo-provisioner-operator-system
spec:
  displayName: RHDP Demo Provisioner
  publisher: Red Hat
  sourceType: grpc
  image: quay.io/redhat-gpte/demo-operator-catalog:1.0.0
  updateStrategy:
    registryPoll:
      interval: 10m
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: demo-provisioner-og
  namespace: demo-provisioner-operator-system
spec:
  targetNamespaces:
  - demo-provisioner-operator-system
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: demo-provisioner-subscription
  namespace: demo-provisioner-operator-system
spec:
  channel: "alpha"
  installPlanApproval: Automatic
  name: demo-provisioner-operator
  source: demo-provisioner-catalog
  sourceNamespace: demo-provisioner-operator-system
  startingCSV: demo-provisioner-operator.v0.0.1
