- hosts: localhost
  gather_facts: False
  vars_files:
    - demos.yaml
  environment:
    CONTROLLER_HOST: "{{ ate_base_data.controller_host }}"
    CONTROLLER_USERNAME: "{{ ate_base_data.controller_username }}"
    CONTROLLER_PASSWORD: "{{ ate_base_data.controller_password }}"
    CONTROLLER_VERIFY_SSL: False
  tasks:
  - name: Create execution environment for Azure
    awx.awx.execution_environment:
      name: "Azure"
      image: "quay.io/pharriso/azure_ee:1.0" 

  - name: Create AWS Credential
    awx.awx.credential:
      name: aws-demo
      credential_type: "Amazon Web Services"
      organization: Default
      inputs:
        username: "{{ ate_creds_aws_data.aws_access_key_id }}"
        password: "{{ ate_creds_aws_data.aws_secret_access_key }}"
      state: present
  - name: Create Azure Credential
    awx.awx.credential:
      name: azure-demo
      credential_type: "Microsoft Azure Resource Manager"
      organization: Default
      inputs:
        client: "{{ ate_creds_azure_data.client_id }}"
        tenant: "{{ ate_creds_azure_data.tenant_id }}"
        subscription: "{{ ate_creds_azure_data.subscription_id }}"
        secret: "{{ ate_creds_azure_data.password }}"
      state: present

  - name: Create Machine Credential
    awx.awx.credential:
      name: machine-demo
      credential_type: "Machine"
      organization: Default
      inputs:
        ssh_key_data: "{{ ate_base_data.ssh_private_key }}"
      state: present

  - name: Create Controller Credential
    awx.awx.credential:
      name: controller-demo
      credential_type: "Red Hat Ansible Automation Platform"
      organization: Default
      inputs:
        host: "{{ ate_base_data.controller_host }}"
        username: "{{ ate_base_data.controller_username }}"
        password: "{{ ate_base_data.controller_password }}"
      state: present



  - name: Create local inventory
    awx.awx.inventory:
      name: local-demo
      organization: Default
      state: present

  - name: Add localhost to local inventory
    awx.awx.host:
      name: localhost
      inventory: local-demo
      variables:
        ansible_connection: local

  - name: Create projects
    awx.awx.project: 
      name: "{{ item['name'] }}"
      organization: Default
      scm_type: git
      scm_url: "{{ item['url'] }}"
    loop: "{{ demos }}"

  - name: Create templates
    include_tasks: create_template.yaml
    loop: "{{ demos }}"

  - name: Create inventories
    include_tasks: create_inventory.yaml
    loop: "{{ demos }}"

  - name: Create credentials
    include_tasks: create_credential.yaml
    loop: "{{ demos }}"

  - name: Run demo templates templates
    include_tasks: run_template.yaml
    loop: "{{ demos }}"

  - name: Replace AWS credential with aws-demo for templates
    when: item['summary_fields']['credentials'] | json_query('[?name==`AWS`]') | length
    awx.awx.job_template:
      name: "{{ item['name'] }}"
      credentials: "{{ item['summary_fields']['credentials'] | json_query('[?name!=`AWS`].name') + ['aws-demo'] }}"
    loop: "{{ query('awx.awx.controller_api', 'job_templates', host=ate_base_data.controller_host,
                             username=ate_base_data.controller_username, 
                             password=ate_base_data.controller_password, verify_ssl=False) }}"
    loop_control:
      label: "{{ item['name'] }}"

  - name: Replace Azure Infrastructure credential with azure-demo for templates
    when: item['summary_fields']['credentials'] | json_query('[?name==`Azure Infrastructure`]') | length
    awx.awx.job_template:
      name: "{{ item['name'] }}"
      credentials: "{{ item['summary_fields']['credentials'] | json_query('[?name!=`Azure Infrastructure`].name') + ['azure-demo'] }}"
    loop: "{{ query('awx.awx.controller_api', 'job_templates', host=ate_base_data.controller_host,
                             username=ate_base_data.controller_username, 
                             password=ate_base_data.controller_password, verify_ssl=False) }}"
    loop_control:
      label: "{{ item['name'] }}"




  - name: Replace AWS credential with aws-demo for inventories
    when: item['summary_fields']['credentials'] | json_query('[?name==`AWS`]') | length
    awx.awx.inventory_source:
      name: "{{ item['name'] }}"
      inventory: "{{ item['inventory'] }}"
      credential: "aws-demo"
      update_on_launch: true
    loop: "{{ query('awx.awx.controller_api', 'inventory_sources', host=ate_base_data.controller_host,
                             username=ate_base_data.controller_username, 
                             password=ate_base_data.controller_password, verify_ssl=False) }}"
    loop_control:
      label: "{{ item['name'] }}"


  - name: Replace Azure Infrastructure credential with aws-demo for inventories
    when: item['summary_fields']['credentials'] | json_query('[?name==`Azure Infrastructure`]') | length
    awx.awx.inventory_source:
      name: "{{ item['name'] }}"
      inventory: "{{ item['inventory'] }}"
      credential: "azure-demo"
      update_on_launch: true
    loop: "{{ query('awx.awx.controller_api', 'inventory_sources', host=ate_base_data.controller_host,
                             username=ate_base_data.controller_username, 
                             password=ate_base_data.controller_password, verify_ssl=False) }}"
    loop_control:
      label: "{{ item['name'] }}"

  - name: Create workflow
    include_tasks: create_workflow.yaml
    loop: "{{ demos }}"




