---
- name: Step 00xxxxx software
  hosts: localhost
  connection: local
  gather_facts: False
  become: false
  tasks:

    - name: "Software tasks Started"
      ansible.builtin.debug:  
        msg: "Software tasks Started"

    - debug: 
        msg: "{{ lookup('config', 'COLLECTIONS_PATHS')[0] }}"

    - name: Install awx.awx collection for packet modules
      command: >-
        ansible-galaxy collection install
        -p "{{ lookup('config', 'COLLECTIONS_PATHS')[0] }}" awx.awx
        --force-with-deps


    - name: Cleanup Automation Controller 
      include_tasks: cleanup.yaml

    - name: Create Automation Controller ATE demo
      include_tasks: create.yaml

- name: Software flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:

    - name: "Software checks completed successfully"
      ansible.builtin.debug:  
        msg: "Software checks completed successfully"

...
