- name: Step 000 Pre Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step000
    - pre_infrastructure
    - generate_env_keys

  tasks:

    - name: "Step 000 Pre Infrastructure"
      ansible.builtin.debug:
        msg: "Step 000 Pre Infrastructure"

    - name: Install amazon.aws:4.0.0
      command: >-
        ansible-galaxy collection install
        -p collections amazon.aws:4.0.0
        --force-with-deps
      args:
        chdir: "{{ playbook_dir }}/../../"
        creates: "{{ playbook_dir }}/../../collections/ansible_collections/amazon/aws"



#    - name: Create SSH provision key
#      when: set_env_authorized_key | bool
#      include_role:
#        name: create_ssh_provision_key

#      community.crypto.openssh_keypair:
#        path: "{{ output_dir }}/{{ env_authorized_key }}"

...
