demos:
  - name: Ansible official demo project
    url: https://github.com/agonzalezrh/product-demos/
    inventories:
      - name: Workshop Inventory
    credentials:
      - name: Workshop Credential
        type: Machine
        inputs:
          username: ec2-user
          ssh_key_data: "{{ ate_base_data.ssh_private_key }}"
    templates:
      - name: setup demo - azure
        playbook: setup_demo.yml
        inventory: local-demo
        extra_vars:
          demo: azure 
          resource_group_name: "{{ ate_creds_azure_data.resource_group }}"
        credentials:
          - azure-demo
          - controller-demo


      - name: setup demo - cloud
        playbook: setup_demo.yml
        inventory: local-demo
        extra_vars:
          demo: cloud
        credentials:
          - aws-demo
          - controller-demo

      - name: setup demo - linux
        playbook: setup_demo.yml
        inventory: local-demo
        extra_vars:
          demo: linux
        credentials:
          - aws-demo
          - controller-demo
      - name: setup demo - windows
        playbook: setup_demo.yml
        inventory: local-demo
        extra_vars:
          demo: windows 
        credentials:
          - aws-demo
          - controller-demo

    launch_templates:
      - name: setup demo - cloud
      - name: setup demo - linux
      - name: setup demo - windows
      - name: setup demo - azure
       
    workflow:
      name: ATE Demo Cloud
      extra_vars: 
        ansible_password: P@ssw0rd
        rhel_public_key: "{{ ate_base_data.ssh_public_key }}"
        iis_message: "ATE Demo"
        survey_public_ip: true
      steps:
        - name: create-infra-aws
          job_template: Cloud / Create Infra
          extra_vars: {'infra_provider': 'aws', 'aws_public_key': "{{ ate_base_data.ssh_public_key}}"}
          success: 
            - identifier: "aws-vm-node1"
            - identifier: "aws-vm-node2"
            - identifier: "aws-vm-win1"
            - identifier: "aws-vm-win2"
        - name: aws-vm-node1
          job_template: Cloud / Create VM
          extra_vars: {'vm_name': 'node1', 'vm_owner': 'ATE demo', 'vm_provider': 'aws', 'vm_blueprint': 'rhel7'} 
          success: 
            - identifier: "linux-patching"
        - name: aws-vm-node2
          job_template: Cloud / Create VM
          extra_vars: {'vm_name': 'node2', 'vm_owner': 'ATE demo', 'vm_provider': 'aws', 'vm_blueprint': 'rhel8'} 
          success: 
            - identifier: "linux-patching"

        - name: aws-vm-win1
          job_template: Cloud / Create VM
          extra_vars: {'vm_name': 'win1', 'vm_owner': 'ATE demo', 'vm_provider': 'aws', 'vm_blueprint': 'windows_full'} 
          success: 
            - identifier: "windows-patching"

        - name: aws-vm-win2
          job_template: Cloud / Create VM
          extra_vars: {'vm_name': 'win2', 'vm_owner': 'ATE demo', 'vm_provider': 'aws', 'vm_blueprint': 'windows_full'} 
          success: 
            - identifier: "windows-patching"

        - name: linux-patching
          job_template: LINUX / Patching
          job_type: "run"
          extra_vars: {'HOSTS': 'node*'} 
          success: 
            - identifier: "linux-podman-webserver"
        - name: linux-podman-webserver
          job_template: LINUX / Podman Webserver
          extra_vars: {'HOSTS': 'node2', 'message': 'Hello world'} 

        - name: windows-patching
          job_template: WINDOWS / Patching
          job_type: "run"
          extra_vars: {'HOSTS': 'win*'} 
          success: 
            - identifier: "windows-install-iis"
  
        - name: windows-install-iis
          job_template: WINDOWS / Install IIS
          job_type: "run"
          extra_vars: {'HOSTS': 'win*'} 

        - name: azure-create-infra
          job_template: AZURE / CREATE INFRA
          success: 
            - identifier: "azure-rhel8-vm"
            - identifier: "azure-windows-vm"

        - name: azure-rhel8-vm
          job_template: AZURE / RHEL 8 VM

        - name: azure-windows-vm
          job_template: AZURE / Windows VM


