---
- name: Generate cluster api                               
  set_fact:                                                
    _ocp4_workload_generate_kubeconfig_openshift_api_url: "https://api{{ ocp4_workload_generate_kubeconfig_console_url | regex_search('(?<=\\.apps).*') }}:6443"                                         
      
#- name: run authentication
#  kubernetes.core.k8s_auth:
#    host: "{{ _ocp4_workload_generate_kubeconfig_openshift_api_url }}"
#    username: "{{ ocp4_workload_generate_kubeconfig_openshift_username }}"
#    password: "{{ ocp4_workload_generate_kubeconfig_openshift_password }}"
#    validate_certs: false
#  register: _r_kube_auth
#  retries: 30
#  delay: 120
#  until:
#    - _r_kube_auth.k8s_auth.api_key is defined

- name: run authentication
  command: oc login --insecure-skip-tls-verify=true -u {{ ocp4_workload_generate_kubeconfig_openshift_username }} -p {{ ocp4_workload_generate_kubeconfig_openshift_password }} {{ _ocp4_workload_generate_kubeconfig_openshift_api_url }}

- name: Create user kube directory
  file:
    path: ~/.kube/
    state: directory
    recurse: true

- name: generate kubeconfig
  template:
    src: kubeconfig.j2
    dest: ~/.kube/config
