---
- name: Run authentication
  k8s_auth:
    host: "{{ ocp4_workload_generate_kubeconfig_openshift_api_url }}"
    username: "{{ ocp4_workload_generate_kubeconfig_openshift_username }}"
    password: "{{ ocp4_workload_generate_kubeconfig_openshift_password }}"
    validate_certs: false
  register: _r_kube_auth
  retries: 30
  delay: 120
  until:
  - _r_kube_auth.k8s_auth.api_key is defined

- name: Create kube directory
  file:
    path: /home/runner/.kube/
    state: directory
    recurse: true

- name: generate kubeconfig
  template:
    src: kubeconfig.j2
    dest: /home/runner/.kube/config

- name: Disable LE installation by default
  set_fact:
    ocp4_workload_le_certificates_install_certificates: false

- name: Create aws credentials
  when:
  - aws_access_key_id is defined
  - aws_secret_access_key is defined
  block:
    - name: Create aws directory
      file:
        path: /home/root/.aws/
        state: directory
        recurse: true

    - name: generate aws credentials
      template:
        src: awscreds.j2
        dest: /home/root/.aws/credentials

    - name: Enable LE installation
      set_fact:
        ocp4_workload_le_certificates_install_certificates: true
