---
- name: Set up bastion
  hosts: bastions
  become: true
  tags:
  - step005
  - post_software
  tasks:
  - debug:
      msg: "Post-Software Steps starting"


  # Deploy Workloads
  - name: Deploy demo operator
    k8s:
      state: present
      definition: "{{ lookup('template', item ) | from_yaml_ }}"
    loop:
    - templates/demo-operator-namespace.yaml
    - templates/demo-operator-catalog-source.yaml
    - templates/demo-operator-operator-group.yaml
    - templates/demo-operator-subscription.yaml
    register: r_operator_install
    retries: 240
    delay: 10
    until:
      - r_operator_install is defined
      - r_operator_install is not failed

  - name: Pause for 5 minutes for demo operator to install
    ansible.builtin.pause:
      minutes: 5

  - name: Deploy demo
    k8s:
      state: present
      definition: "{{ lookup('template', item ) | from_yaml }}"
    loop:
    - templates/demo-workshop-install.yaml.j2
    register: r_demo
    retries: 240
    delay: 10
    until:
      - r_demo is defined
      - r_demo is not failed

  - name: Check if demo has completed install
    k8s_info:
      api_version: demos.redhat.com/v1
      kind: Demo
      name: demo-getting-started-ocp
      namespace: demo-provisioner-operator-system
    register: result_demo_install
    retries: 480
    delay: 15
    until:
      - result_demo_install is defined
      - result_demo_install.resources is defined
      - result_demo_install.resources | length > 0
      - result_demo_install.resources[0].status is defined
      - result_demo_install.resources[0].status.phase is defined
      - result_demo_install.resources[0].status.phase != 'Running'

  - name: Check if demo failed installation
    ansible.builtin.fail:
      msg: The demo did not provision successfully.  Please view the logs on the demo pod.
    when: result_demo_install.resources[0].status.phase == 'Failed'


  - name: PostSoftware flight-check
    hosts: localhost
    connection: local
    gather_facts: false
    become: false
    tags:
    - post_flight_check
    tasks:
    - debug:
        msg: "Post-Software checks completed successfully"
