---
- name: Step 000 Post Software
  hosts: localhost
  connection: local
  become: false
  tags:
    - step001
    - post_software
  tasks:
    - debug:
        msg: "Step 000 Post Software - Starting"

    - name: Save Azure OPEN Environment Details
      agnosticd_user_info:
        data:
          resource_group: "openenv-{{ guid }}"
          client_id: "{{ azapp['applications'][0].app_id }}"
          password: "{{ azpass }}"
          tenant_id: "{{ azure_tenant }}"
          subscription_id: "{{ azure_subscription_id }}"

- name: Step 002 Post Software
  hosts: localhost
  connection: local
  become: false
  tags:
    - step001
    - post_software
  tasks:
    - debug:
        msg: "Step 002 Post Software - Completed"

- name: Software flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Post-Software checks completed successfully"
