---
- name: Step 000 software
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - debug:
        msg: "Software tasks Started"

- name: Step 00xxxxx software
  hosts: bastions
  gather_facts: false
  become: false
  tasks:
    - tags:
        - install_studentvm_role
      block:
        - name: Run student role
          when: studentvm_roles | default( "" ) | length > 0
          include_role:
            name: "{{ studentvm_role }}"
          loop: "{{ studentvm_roles }}"
          loop_control:
            loop_var: studentvm_role

- name: Install ARO
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  environment:
    AZURE_CONFIG_DIR: "{{ output_dir }}/.azure-{{ project_tag }}"
    KUBECONFIG: "{{ output_dir }}/{{ guid }}-kubeconfig"
  tasks:
    - name: Install ARO
      when: install_aro | bool
      include_role:
        name: open-env-azure-install-aro

- name: Software flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Software checks completed successfully"
