---
- name: Step 000 software
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - debug:
        msg: "Software tasks Started"

- name: Step 00xxxxx software
  hosts: bastions
  gather_facts: false
  become: false
  tasks:
    - tags:
        - install_studentvm_role
      block:
        - name: Run student role
          when: studentvm_roles | default( "" ) | length > 0
          include_role:
            name: "{{ studentvm_role }}"
          loop: "{{ studentvm_roles }}"
          loop_control:
            loop_var: studentvm_role

- name: Install ARO
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  environment:
    AZURE_CONFIG_DIR: "{{ output_dir }}/.azure-{{ project_tag }}"
    KUBECONFIG: "{{ output_dir }}/{{ guid }}-kubeconfig"
  tasks:
    - name: Install ARO
      when: install_aro | bool
      include_role:
        name: open-env-azure-install-aro

- name: Step 00xxxxx software
  hosts: bastions
  gather_facts: false
  become: false
  tasks:
    - tags:
        - install_kube_config
      block:
        - name: Install kubeconfig
          when: not preconfigure_aad
          block:
            - name: Set kube config directory
              set_fact: kubeconfigdir="{{ output_dir }}/.kube"

            - name: Set kube config file path
              set_fact: kubeconfig="{{ kubeconfigdir }}/config"

            - name: Make sure .kube directory exists
              ansible.builtin.file:
                state: directory
                path: "{{ kubeconfigdir }}"
                mode: 0700

            - name: Login to the resulting ARO cluster as kubeadmin
              command: >-
                oc login {{ az_aro4_public_api_url }} -u kubeadmin -p {{ az_aro4_kubeadmin_password.stdout }} --kubeconfig {{ kubeconfig }} --insecure-skip-tls-verify
              register: r_cluster_login
              retries: 6
              delay: 60
              until: r_cluster_login is success

- name: Software flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Software checks completed successfully"
