---
- name: install python3-virtualenv
  ansible.builtin.yum:
    name: python3-virtualenv
    state: present

- name: install certbot and nginx plugin
  ansible.builtin.pip:
    name:
      - certbot
      - certbot-nginx
    virtualenv: /opt/certbot
    state: present

- name: Generate certbot
  command: >-
    /opt/certbot/bin/certbot certonly --nginx
    -m {{ email | regex_replace('example.com$','opentlc.com') }}
    --agree-tos
    -d {{ pah_server_hostname  }} -n

# - name: Create nginx certificate directory
#   file:
#     path: /etc/pki/nginx/private
#     state: directory
#     recurse: yes
#     owner: nginx

- name: Copy letsencrypt key
  copy:
    src: /etc/letsencrypt/live/{{ pah_server_hostname }}/privkey.pem
    dest: /etc/pulp/certs/pulp_webserver.key
    remote_src: yes
    owner: nginx
    mode: 0644

- name: Copy letsencrypt certificate
  copy:
    src: /etc/letsencrypt/live/{{ pah_server_hostname }}/cert.pem
    dest: /etc/pulp/certs/pulp_webserver.crt
    remote_src: yes
    owner: nginx
    mode: 0644

- name: Restart nginx server
  service:
    name: nginx
    enabled: yes
    state: restarted

- name: deploy CA Certificate files
  copy:
    src: lets-encrypt-r3.pem
    dest: /etc/pki/ca-trust/source/anchors/
    owner: root
    group: root
    mode: 0644

- name: update CA trusts
  shell: update-ca-trust
...
