---
- name: Create webrhv VM
  ovirt.ovirt.ovirt_vm:
    auth:
      insecure: true
    state: present
    name: "webrhv-{{ guid }}"
    template: "webrhv-tpl"
    cluster: "{{ ocp4_workload_ama_demo_vm_cluster }}"
    storage_domain: "{{ ocp4_workload_ama_demo_rhev_storage }}"
