---
collections:

  - name: ansible.posix
  - name: infra.controller_configuration
  - name: ansible.workshops
  - name: containers.podman
  - name: awx.awx
  - name: amazon.aws
  - name: community.aws


  - name: community.crypto
  - name: community.general


  - name: community.okd