---
- name: Create Devspaces application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'application-devspaces.yml.j2' ) | from_yaml }}"

- name: Create devspace resources
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
    - namespace-devspaces-dev-user.yml.j2
    - secret-devspaces-gitcreds.yml.j2