---
- name: Create RHSSO application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'application-rhsso-backstage.yml.j2' ) | from_yaml }}"

- name: Retrieve realm client credentials
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: keycloak-client-secret-backstage
    namespace: "{{ ocp4_workload_redhat_developer_hub_backstage_namespace }}"
  register: r_realm_credentials
  retries: 120
  delay: 10
  until:
  - r_realm_credentials is defined
  - r_realm_credentials.resources is defined
  - r_realm_credentials.resources | length > 0

- name: Decode realm credentials
  set_fact:
    ocp4_workload_redhat_developer_hub_keycloak_client_id: "{{ r_realm_credentials.resources[0].data.CLIENT_ID | b64decode }}"
    ocp4_workload_redhat_developer_hub_keycloak_client_secret: "{{ r_realm_credentials.resources[0].data.CLIENT_SECRET | b64decode }}"