---
- name: install gitwebhook operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_name: gitwebhook-operator
    install_operator_namespace: ogitwebhook-operator
    install_operator_channel: alpha
    install_operator_starting_csv: gitwebhook-operator.v0.1.0
    install_operator_catalog: community-operators
    install_operator_catalogsource_setup: false