---
- name: Install Helm
  shell: |
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    chmod 700 get_helm.sh
    ./get_helm.sh

- name: Clone janus demo repository
  ansible.builtin.git:
    accept_hostkey: true
    force: true
    repo: "{{ ocp4_workload_redhat_developer_hub_janus_repo }}"
    dest: "~/demo-setup"
    version: main
  environment:
    GIT_SSL_NO_VERIFY: "true"

- name: Remove operator subscription
  shell: |
    rm -f ~/demo-setup/charts/gitops-operator/templates/subscription.yaml

- name: Install GitOps Helm Chart
  kubernetes.core.helm:
    state: present
    name: argocd
    namespace: janus-argocd
    chart_ref: ~/demo-setup/charts/gitops-operator
    values:
      namespaces:
        - janus-argocd
      projects:
        - name: janus
          namespace: janus-argocd
          role: automation
    create_namespace: true