---
- name: Setting up workload
  debug:
    msg: "Setting up GitLab"

- name: Retrieve Ingress config
  k8s_info:
    api_version: config.openshift.io/v1
    kind: Ingress
    name: cluster
  register: r_ingress_config

- name: Get OpenShift Apps Domain
  set_fact:
    ocp4_workload_redhat_developer_hub_apps_domain: "{{ r_ingress_config.resources[0].spec.domain }}"
    ocp4_workload_redhat_developer_hub_gitlab_host: "gitlab-{{ ocp4_workload_redhat_developer_hub_gitlab_namespace }}.{{ r_ingress_config.resources[0].spec.domain }}"
    ocp4_workload_redhat_developer_hub_keycloak_host: "keycloak-{{ ocp4_workload_redhat_developer_hub_backstage_namespace }}.{{ r_ingress_config.resources[0].spec.domain }}"
    ocp4_workload_redhat_developer_hub_backstage_host: "backstage-{{ ocp4_workload_redhat_developer_hub_backstage_namespace }}.{{ r_ingress_config.resources[0].spec.domain }}"
    ocp4_workload_redhat_developer_hub_devspaces_host: "devspaces.{{ r_ingress_config.resources[0].spec.domain }}"

- name: Setup Gitlab dependencies
  include_tasks:
    file: ./setup_gitlab.yml

- name: Setup Gitlab dependencies
  include_tasks:
    file: ./setup_rhsso.yml

- name: Setup Gitlab dependencies
  include_tasks:
    file: ./setup_backstage.yml

- name: Setup Gitlab dependencies
  include_tasks:
    file: ./setup_templates.yml

- name: Setup Gitlab dependencies
  include_tasks:
    file: ./setup_devspaces.yml

- name: Print user info
  agnosticd_user_info:
    msg: "{{ item }}"
  loop:
  - ""
  - "Your Backstage login credentials:"
  - "Backstage: https://{{ ocp4_workload_redhat_developer_hub_backstage_host }}"
  - "Backstage identity provider: GitLab"
  - "Backstage user: {{ ocp4_workload_redhat_developer_hub_backstage_gitlab_username }}"
  - "Backstage password: {{ ocp4_workload_redhat_developer_hub_backstage_gitlab_password }}"

- name: Print user info
  when: ocp4_workload_redhat_developer_hub_backstage_gitlab_user_create
  agnosticd_user_info:
    msg: "{{ item }}"
  loop:
  - ""
  - "Your GitLab login credentials:"
  - "GitLab: https://{{ ocp4_workload_redhat_developer_hub_gitlab_host }}"
  - "GitLab user: {{ ocp4_workload_redhat_developer_hub_backstage_gitlab_username }}"
  - "GitLab password: {{ ocp4_workload_redhat_developer_hub_backstage_gitlab_password }}"

# Leave this as the last task in the playbook.
# --------------------------------------------
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool
