---

- name: Step 00xxxxx software
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  collections:
    - awx.awx

  tasks:

    # - name: Configure controller with workflow
    #   ansible.builtin.import_role:
    #     name: controller_content

    - name: "Software tasks Started"
      ansible.builtin.debug:
        msg: "Binder Software tasks Started"

    - name: Create AAP2 Projects
      when: controller_configuration_dispatcher_roles is defined
      ansible.builtin.import_role:
        name: infra.controller_configuration.dispatch

    - name: "Software checks completed successfully"
      ansible.builtin.debug:
        msg: "Software checks completed successfully"
      tags:
        - post_flight_check
...
